# Use the correct path to the react_native_pods.rb script
require File.expand_path('../node_modules/react-native/scripts/react_native_pods', __dir__)

platform :ios, '12.0' # Ensure the minimum iOS version is set correctly
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AquaFlush' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Path to the root of your application
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AquaFlushTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Post-install script to correctly link and setup React Native
    react_native_post_install(installer)
  end
end
