require File.join(`node --print "require.resolve('react-native/scripts/react_native_pods.rb', {paths: [__dir__]})"`.strip)

platform :ios, '12.0' # Update to the minimum iOS version supported by your project.
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AquaFlush' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AquaFlushTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Adjust the react_native_post_install call to reflect any necessary options.
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
